### PR TITLE
Added downloading of speeches

### PR DESCRIPTION
**Pull request by biosafetylvl5**
Added basic functionality for downloading a speech. 

Usage example:

```
# ID = some otter speech id
otter.download_speech(ID) # downloads ID.zip with all formats available for ID
otter.download_speech(ID, fileformat="pdf") # downloads ID.pdf
otter.download_speech(ID, fileformat="pdf", name="speech") # downloads ID pdf as speech.pdf
```

Had to make small edit to _handle_response, I think the code explains itself well but I'm also happy to answer questions!

:slightly_smiling_face:

### CODE REVIEW

**Comment by anoduck** [comment]
@biosafetylvl5 Just to confirm, without this pr, the api is unable to download speeches?

**Comment by aviaryan** [comment]
@biosafetylvl5 Thanks for this PR. Will it be able to use this to download all the speeches? I have 1000s of conversations on Otter and I would like to export them.

**Comment by anoduck** [comment]
> @biosafetylvl5 Thanks for this PR. Will it be able to use this to download all the speeches? I have 1000s of conversations on Otter and I would like to export them.

Did you ever find a solution to your exporting issue? I am going to fork @biosafetylvl5 additions and begin to look into what it would take to add transcript exportation to the API. There is more than likely a reason @gmchad and @biosafetylvl5 did not implement it, and experience tells me it has a high probability of being more hassle than it is reasonably worth.

**Comment by aviaryan** [comment]
> Did you ever find a solution to your exporting issue?

Yes, I can export, and I have downloaded thousands of notes from Otter. These downloads also contain the transcription.

**Comment by anoduck** [comment]
> > Did you ever find a solution to your exporting issue?
> 
> Yes, I can export, and I have downloaded thousands of notes from Otter. These downloads also contain the transcription.

I just learned, myself, no less than 3 days ago, this pull request allows the downloading of transcripts. This is so awesome! @gmchad needs to merge it.

**Comment by gmchad** [comment]
Tested it for a transcript, looks good. Sorry, this took so long to merge.

**Comment by biosafetylvl5** [comment]
Thanks @gmchad, sorry to other folks for not responding.

**Pull request merged**
